### ISSUE TITLE
Error: FFT: can only compute FFT of arrays which have an even size

### ISSUE THREAD

**Issue by kubs0ne** [Xylch/audio-siren-detection#1]
Hello,
I wanted to test your code in python, but when I pass the file that I want to analyse, the following error occurs:

> RuntimeError: In FFT.compute: FFT: can only compute FFT of arrays which have an even size

It's weird that FFT needs an array that has more than one dimension. Do you have any idea why it is or how to fix it?
Regards

**Comment by Xylch** [comment]
I haven't looked at that code since I wrote it in University. I just took a look at it now and it appears to be incomplete. I don't think I have that old code anymore so I can't really help you.
